git_head = "d0fecb3264aeb855ab6700fc6ef66120d4b6c33c"
timestamp_utc = "2026-09-29T01:20:03.560"
julia_version = "1.11.9"
powerdynamics_version = "5.0.0"
randomness = "none"
blas = "LBTConfig([ILP64] libopenblas64_.dll)"
git_branch = "main"
